# Generated by Django 3.2.7 on 2021-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creepers', '0002_rename_owner_creeper_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='creeper',
            name='survivability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='1'),
        ),
    ]
